#ifndef INPUT_H
#define INPUT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// AES inputs generation mode constants.
#define SC_INPUT_MODE_GEN 1 // AES inputs are generated by Nimble during pairing.
#define SC_INPUT_MODE_SUB 2 // AES inputs are submitted by a computer from the serial port.

// Used by other modules to set/get what is the AES input generation
// method. Should be set to SC_INPUT_MODE_GEN or SC_INPUT_MODE_SUB.
extern int SC_INPUT_MODE;
// Used by other modules to set/get the current state of AES inputs
// submission. Should be set to a boolean.
extern int SC_INPUT_SUB_OK;

// Return a string indicating what is the AES input generation method.
char * sc_input_get_input_mode_str();

#ifdef __cplusplus
}
#endif

#endif
