#ifndef INPUT_H
#define INPUT_H

#include <stdint.h>
#include "nimble/ble.h"
#include "host/ble_store.h"

#ifdef __cplusplus
extern "C" {
#endif

// AES inputs generation mode constants.
#define SC_INPUT_MODE_GEN 1 // AES inputs are generated by Nimble during pairing.
#define SC_INPUT_MODE_SUB 2 // AES inputs are submitted by a computer from the serial port.

#define INPUT_SIZE 16 // 128-bits for keys and plaintexts.

// Used by other modules to set/get what is the AES input generation
// method. Should be set to SC_INPUT_MODE_GEN or SC_INPUT_MODE_SUB.
extern int SC_INPUT_MODE;
// Used by other modules to set/get the current state of AES inputs
// submission. Should be set to a boolean. If set to 1, this means that the
// current key (SC_INPUT_KS) and current plaintext (SC_INPUT_PT) have been
// registered inside the Nimble security database.
extern int SC_INPUT_SUB_OK;

/**
 * Inputs values.
 *
 * Should be set to a correct value if SC_INPUT_SUB_OK is set to 1.
 * Are arrays of size INPUT_SIZE.
*/
extern uint8_t SC_INPUT_KS[INPUT_SIZE]; // Key used for the AES (LTK).
extern uint8_t SC_INPUT_PT[INPUT_SIZE]; // Plaintext used for the AES (SKD).

/** Security material with its address that will be added into security database. */
extern struct ble_store_value_sec SC_INPUT_VALUE_SEC;
extern ble_addr_t SC_INPUT_PEER_ADDR;

// Return a string indicating what is the AES input generation method.
char * sc_input_get_input_mode_str();

/** Submit the custom Screaming Channels input to the Nimble subsystem.
 *
 * This implies to register a structure inside the Nimble security database
 * with the LTK/RAND/EDIV set such that it allows to connect without
 * pairing. Moreover, it exposes the key (i.e., the LTK) and the plaintext
 * (i.e., the SKDs) to the AES submodule.
 *
 * The function return the code returned by the 'ble_store_write_our_sec()'
 * function, i.e. 0 if there is not errors.
 */
int sc_input_sub();

#ifdef __cplusplus
}
#endif

#endif
